model_name: wide_resnet
pretrained: False
depth: 28
width: 2

bn_momentum:
bn_eps:
scriptable: False

drop_rate: 0
drop_path_rate:
drop_block_rate:

gp: # (fast, avg, max, avgmax, avgmaxc)
features_only: False
