no_aug: False

mean:
std:

scale: [ 0.08, 1.0 ]
ratio: [ 0.75, 1.33 ]
hflip: 0.5
vflip: 0
auto_aug:
crop_pct: 0.875

epoch_repeats: 0
aug_repeats: 0
aug_splits: 0

re_prob: 0
mixup: 0
cutmix: 0

smoothing: 0.0
train_interpolation: random # [random, bilinear, bicubic]
test_interpolation: bicubic
